language: node_js

sudo: false

# After creating your SDK project from this template repository,
# uncomment this section to enable builds on the appropriate node versions.
# node_js:
# - 10
# - 12

before_install:
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
# -  'openssl aes-256-cbc -K $my_key -iv $my_iv -in myservice.env.enc -out myservice.env -d || true'

script:
- npm run build
- npm run test-travis || travis_terminate 1
- npm run lint
- npm run check-packages
# - sh scripts/typedoc/generate_typedoc.sh currently in progress

# After creating your SDK project from this template repository,
# remove this entire "jobs" section as this is only applicable
# to the template repo's travis build.
jobs:
  include:
    - stage: Run node template build
      node_js: 10
    - node_js: 12
    - stage: Run system test with template
      node_js: 10
      script:
        - git clone https://github.ibm.com/CloudEngineering/sdkgen-systest.git
        - cd sdkgen-systest
        - ./install_scripts/install_deps_ubuntu.sh
        - ./setup_and_generate.sh -l ibm-node -t $TRAVIS_BRANCH -s


after_success:
- npm run report-coverage

# To enable semantic-release, uncomment this section.
# deploy:
# - provider: script
#   skip_cleanup: true
#   script: npx semantic-release
#   on:
#     node: 12
#     branch: main
